#!/bin/bash
#
# Copyright (C) 2017  Attila Orosz
#
# This file is part of Lazy Admin
#
# Lazy Admin is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with Lazy Admin. If not, see <http://www.gnu.org/licenses/>.
#
# Contact: attila.orosz@mail.com


COREDIRPLACEHOLDER
USER_DIR="$HOME/.config/LazyAdmin"

. "$CORE_DIR/includes.la"


if [[ $1 == ""  ]]; then
    
    arg1="default"

else

    arg1=$1 
    
fi

if [[ $2 == "" ]];  then

    arg2="true"
    
else

    arg2=$2
    
fi



# In case the user starts ladmin for the first time...
if [[ "$CORE_DIR" != "$HOME/.LazyAdmin" ]]; then

    
  if [[ ! -d "$USER_DIR" ]]; then
  
    mkdir "$USER_DIR"
    
    tar -xvzC "$USER_DIR" -f "$INSTALL_DIR/res/user_defaults.tar"
        
  
  fi
    

fi


main $arg1 $arg2
