#!/bin/bash
#
# Copyright © 2017-2025, Attila Orosz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

INSTALLDIRPLACEHOLDER
declare USER_DIR_BASE="$HOME/.config/LazyAdmin"
declare USER_PROFILE="$USER_DIR_BASE/user"

# In case the user starts ladmin for the first time...
if [[ "$INSTALL_DIR" != "$HOME/.LazyAdmin" ]]; then

    if [[ ! -d "$USER_DIR_BASE" ]]; then
        mkdir "$USER_DIR_BASE"
        tar -xvzC "$USER_DIR_BASE" -f "$INSTALL_DIR/res/user_files.tar.gz"
    fi

fi

for ((i = 1; i <= $#; i++)); do
    j=$((i + 1))

    case "${!i}" in
    "-p" | "--load-profile")
        USER_PROFILE=""
        PROFILE_NAME=${!j}
        absolute_path=false

        if [[ ${profile_name:0:1} == "/" ]]; then
            absolute_path=true
        fi

        if $absolute_path && [[ -d "$profile_name" ]]; then
            USER_PROFILE="$profile_name"
        else

            if [[ -d "$USER_DIR_BASE/$profile_name" ]]; then
                USER_PROFILE="$USER_DIR_BASE/$profile_name"
            fi

        fi

        if [[ -z $USER_PROFILE ]]; then
            echo
            echo "Error: User profile $profile_name not found. Exiting"
            echo
            exit 65

        fi
        ;;
    esac
done

. "$INSTALL_DIR/core/includes.la"

main "$@"
