#!/bin/bash
#
# Copyright © 2017-2025, Attila Orosz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
user_profile="$CURRENT_DIR/user"

for ((i = 1; i <= $#; i++)); do
    j=$((i + 1))

    case "${!i}" in
    "-p" | "--load-profile")
        user_profile=""
        profile_name=${!j}
        absolute_path=false

        if [[ ${profile_name:0:1} == "/" ]]; then
            absolute_path=true
        fi

        if $absolute_path && [[ -d "$profile_name" ]]; then
            user_profile="$profile_name"
        else

            if [[ -d "$CURRENT_DIR/$profile_name" ]]; then
                user_profile="$CURRENT_DIR/$profile_name"
            fi

        fi

        if [[ -z $user_profile ]]; then
            echo
            echo "Error: User profile $profile_name not found. Exiting"
            echo
            exit 65
        fi
        ;;
    esac
done

USER_DIR="$user_profile"
CORE_DIR="$CURRENT_DIR/core"

. "$CORE_DIR/includes-port.la"

main "$@"
