#!/bin/bash

# Lazy Admin is a simple bash based pseudo UI to easily store and execute bash commands and user functions
#   Copyright (C) 2015  Attila Orosz
#
# This file is part of Lazy Admin
#
# n-menus is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Lazy Admin.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: attila.orosz@mail.com

tabpos=0
menupos=0
altmenu=false
submenu="false"
subflagsmenu="false"
menufile="$HOME/.config/lazy_admin/user/la-menuentries"
helpfile="$HOME/.config/lazy_admin/core/la-help"
cursorpos=0
normalmenuheight=8
submenuheight=11
maintitle="Lazy Admin"
roottitle=" -- ROOT Shell"
rightpanel=true
bottomseparators=3
rightpanelwidth=27
activepanel="left"
descriptorheight=1
mainheaderheight=4
subheaderheight=2
root="false"

